W-15895638-rtf-core-permissions-kt
mulesoft/docs-runtime-fabric pull request #1290
Opened 2024-06-04 17:37 UTC by kevintroller

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-06-04 17:58 UTC, dukesphere commented on modules/ROOT/pages/rtf-permissions.adoc
> +These RBAC (Role-based access control) configurations (ClusterRole and Rolebindings) are part of the Runtime Fabric helm charts and are automatically applied during the installation.
Do these need special formatting (code or bold)? 

> (ClusterRole and Rolebindings)

2024-06-04 18:00 UTC, dukesphere commented on modules/ROOT/pages/rtf-permissions.adoc
> +You can't extend or modify any of these core software access permissions. You need to create and apply the ClusterRole and Rolebindings for the Runtime Fabric Authorized namespaces use case. Refer to
Not sure. if we care about "You need to". Also not sure about formatting of "ClusterRole and Rolebindings".

```suggestion
You can't extend or modify any of these core software access permissions. Instead, create and apply the ClusterRole and Rolebindings for the Runtime Fabric Authorized namespaces use case. Refer to xref:authorized-namespaces.adoc[].
```

2024-06-04 18:02 UTC, dukesphere commented on modules/ROOT/pages/rtf-permissions.adoc
> +Mule apps deployed on the Runtime Fabric platform do not expect to access the underlying Kubernetes API server. By default, Mule apps deployments do not have RBAC configurations (Role and Rolebinding
Not sure we use "expect to" for products, but your call. And not sure about formatting of "(Role and Rolebindings)"

```suggestion
Mule apps deployed on the Runtime Fabric platform do not expect to access the underlying Kubernetes API server. By default, Mule app deployments do not have RBAC configurations (Role and Rolebindings).
```

2024-06-04 18:04 UTC, dukesphere commented on modules/ROOT/pages/rtf-permissions.adoc
> +However, if the Mule app use case requires K8s API access, you can override this behavior by enabling the `automountserviceaccounttoken` via customization CRD and attach a Role (customer-owned) with
* Do we allow short form "K8s" for Kubernetes? 
* Not clear what "via customization CRD" means. Is that "through a Custom Resource Definition" ?

2024-06-04 18:43 UTC, hegderohit89 commented on modules/ROOT/pages/configure-kubernetes.adoc
> +* xref:rtf-permissions.adoc[Runtime Fabric Core Software Permissions]
@kevintroller the way you have organized the rtfctl and core software permissions are good but how about we group all the permissions in one line and have sub-bullets.. something like this:

* xref:runtime-fabric-permissions[Runtime Fabric Kubernetes Permissions]
  ** rtf-permissions.adoc[Runtime Fabric Core Software Permissions]
  ** rtfctl-permissions.adoc[Enabling RTFCTL Kubernetes Permissions]
  ** mule-app-permissions.adoc[Mule App Deployment Kubernetes Permissions on RTF]

And these 3 can be independent docs page ?

CC: @karanshah-mulesoft @a-palchikov

2024-06-04 19:40 UTC, a-palchikov reviewed
I have some concerns about naming - I believe it's customary in a kubernetes context to call the core components "control plane". It might be ambiguous to the mulesoft control plane but if we're careful to use it in combination with "RTF" (or "Runtime Fabric") it should be unambiguous?

2024-06-04 19:40 UTC, a-palchikov commented on modules/ROOT/pages/rtf-permissions.adoc
> +However, if the Mule app use case requires K8s (Kubernetes) API access, you can override this behavior by enabling the `automountserviceaccounttoken` via customization CRD (custom resource definition
```suggestion
However, if a Mule application requires Kubernetes API access, it can be enabled by overriding the `automountserviceaccounttoken` setting via an infrastructure template. A customer-owned `Role` and the corresponding `RoleBinding` should be created for the service account that RTF automatically generates for each deployment. Refer to xref:/customize-kubernetes-crd.adoc[].
```
this would greatly benefit from an actual example of an infrastructure template to accomplish this example.

2024-06-04 19:40 UTC, a-palchikov commented on modules/ROOT/pages/rtf-permissions.adoc
> +== Runtime Fabric Core Software Permissions
```suggestion
== Runtime Fabric control plane access permissions
```

2024-06-04 19:40 UTC, a-palchikov commented on modules/ROOT/pages/rtf-permissions.adoc
> +The following table lists all the Kubernetes resource access authorizations used by Runtime Fabric core software.
```suggestion
The following table lists the Kubernetes access permissions required by the Runtime Fabric control plane.
```

2024-06-04 19:40 UTC, a-palchikov commented on modules/ROOT/pages/rtf-permissions.adoc
> +These RBAC (Role-based access control) configurations (`ClusterRole` and `Rolebindings`) are part of the Runtime Fabric helm charts and are automatically applied during the installation.
```suggestion
These access permissions are part of the Runtime Fabric helm chart and are automatically applied during the installation/upgrade.
```

2024-06-04 19:40 UTC, a-palchikov commented on modules/ROOT/pages/configure-kubernetes.adoc
> +Review all the Kubernetes resource access authorizations used by Runtime Fabric core software.
```suggestion
Review the Kubernetes resource access permissions required by the Runtime Fabric control plane.
```

2024-06-04 20:41 UTC, dukesphere approved these changes, later dismissed

2024-06-05 19:01 UTC, dmerlob approved these changes, later dismissed

2024-06-05 21:33 UTC, SparshAgarwal commented on modules/ROOT/pages/rtf-permissions.adoc
> += Runtime Fabric Control Plane Access Permissions
Runtime Fabric Agent* Access Permissions

2024-06-05 21:33 UTC, SparshAgarwal commented on modules/ROOT/pages/rtf-permissions.adoc
> +The following table lists the Kubernetes access permissions required by the Runtime Fabric control plane.
required by the Runtime Fabric Agent.

2024-06-05 21:34 UTC, SparshAgarwal commented on modules/ROOT/pages/rtf-kubernetes-permissions.adoc
> +* xref:rtf-permissions.adoc[Runtime Fabric Control Plane Access Permissions] +
Runtime Fabric Agent Access Permissions

2024-06-05 21:34 UTC, SparshAgarwal commented on modules/ROOT/pages/rtf-kubernetes-permissions.adoc
> +Review the Kubernetes resource access permissions required by the Runtime Fabric control plane.
Runtime Fabric Agent

2024-06-05 21:35 UTC, SparshAgarwal commented on modules/ROOT/nav.adoc
> +    *** xref:rtf-permissions.adoc[Runtime Fabric Control Plane Access Permissions]
Runtime Fabric Agent

2024-06-05 21:38 UTC, hegderohit89 commented on modules/ROOT/nav.adoc
> +    *** xref:rtf-permissions.adoc[Runtime Fabric Control Plane Access Permissions]
`Runtime Fabric Core software Kubernetes Permissions`

2024-06-05 21:38 UTC, hegderohit89 requested changes, later dismissed

2024-06-05 21:38 UTC, hegderohit89 commented on modules/ROOT/pages/rtf-kubernetes-permissions.adoc
> +* xref:rtf-permissions.adoc[Runtime Fabric Control Plane Access Permissions] +
`Runtime Fabric Core software Kubernetes Permissions`

2024-06-05 21:38 UTC, hegderohit89 commented on modules/ROOT/pages/rtf-kubernetes-permissions.adoc
> +Review the Kubernetes resource access permissions required by the Runtime Fabric control plane.
+1

2024-06-05 22:42 UTC, Crispy-Salesforce approved these changes

2024-06-07 16:07 UTC, Crispy-Salesforce approved these changes

2024-06-07 23:47 UTC, merged