Minimum of controller nodes for dev was wrong
mulesoft/docs-runtime-fabric pull request #145
Opened 2019-11-04 14:18 UTC by lterenMS

2019-11-04 16:06 UTC, sundippatel commented on modules/ROOT/pages/install-sys-reqs.adoc
> +The number of controller nodes required for a production environment is one. Even numbers of
Another bug fix: sub "production" for "development"

2019-11-04 16:06 UTC, sundippatel requested changes
Good catch; found another bug we should update before merging

2019-11-08 01:40 UTC, sundippatel approved these changes

2019-11-08 11:27 UTC, paigehargrave approved these changes

2019-11-08 11:27 UTC, merged