Update deploy-resource-allocation.adoc
mulesoft/docs-runtime-fabric pull request #425
Opened 2021-08-05 03:53 UTC by yuxiaojian

Discussed with product team and update the document per the conclusion

2021-08-12 21:08 UTC, vli63127 requested changes, later dismissed
Change License to lower case, then i'm good.

2021-08-12 22:38 UTC, yuxiaojian reviewed
@vli63127 done

2021-10-25 22:02 UTC, IsaacEldridge approved these changes

2021-10-25 22:02 UTC, IsaacEldridge approved these changes

2021-10-25 22:03 UTC, IsaacEldridge approved these changes

2021-10-25 22:03 UTC, IsaacEldridge approved these changes

2021-10-25 22:05 UTC, IsaacEldridge approved these changes

2021-10-25 22:05 UTC, merged