W-10737841 updating rtfctl docs
mulesoft/docs-runtime-fabric pull request #616
Opened 2022-02-22 23:08 UTC by IsaacEldridge

2022-02-22 23:16 UTC, digvijaysk19 commented on modules/ROOT/pages/install-rtfctl.adoc
> +* Displays registry credentials
@IsaacEldridge can you please add **rtf** registry credentials. So that we specifically convey that they are for rtf registry.

2022-02-22 23:39 UTC, digvijaysk19 requested changes
left inline comments

2022-02-22 23:43 UTC, IsaacEldridge commented on modules/ROOT/pages/install-rtfctl.adoc
> +* Displays registry credentials
```suggestion
* Displays Runtime Fabric registry credentials
```

2022-02-22 23:44 UTC, digvijaysk19 approved these changes
lgtm

2022-02-23 00:01 UTC, wwarner-salesforce approved these changes

2022-02-23 16:29 UTC, merged