adding endpoints
mulesoft/docs-runtime-fabric pull request #684
Opened 2022-04-20 18:38 UTC by IsaacEldridge

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2022-04-21 15:18 UTC, PabloCamino commented
Hi @IsaacEldridge , as this is for W-11026322 let's also add a clarification on the following section <https://docs.mulesoft.com/runtime-fabric/1.12/manage-proxy#configure-an-http-proxy> clarifying that:
* HTTP/HTTPS proxy is used for communication with the management plane except for monitoring
* Anypoint Monitoring uses its own proxy setting (And a link to this section)
* Mule applications use their own proxy settings

I can see we have 4 different proxies documented on the same page:
1. Cluster level management plane proxy https://docs.mulesoft.com/runtime-fabric/1.12/manage-proxy#apply-proxy-values-to-runtime-fabric
2. Cluster level Anypoint Monitoring proxy https://docs.mulesoft.com/runtime-fabric/1.12/manage-proxy#configure-a-monitoring-proxy
3. Application level proxy https://docs.mulesoft.com/runtime-fabric/1.12/manage-proxy#configure-a-proxy-for-an-application
4. Application level API Manager proxy https://docs.mulesoft.com/runtime-fabric/1.12/manage-proxy#configure-a-proxy-for-the-api-manager-agent
Shall we start with a table at the top summarizing that there is four of them and what is each one for?

@rtom-mulesoft , you spent an hour with the customer because of this lack of clarity, what do you think?

2022-04-21 16:40 UTC, IsaacEldridge commented on modules/ROOT/pages/manage-proxy.adoc
> +To configure a proxy for the API Manager Agent, add the following properties to the application:
@PabloCamino I'm not sure this sentence makes sense. "...add the following properties to the application." Which application?

2022-04-21 16:53 UTC, IsaacEldridge commented on modules/ROOT/pages/manage-proxy.adoc
> +* xref:configure-an-anypoint-monitoring-proxy[Configure an Anypoint Monitoring Proxy]
@PabloCamino added the list here as requested

2022-04-22 16:05 UTC, PabloCamino requested changes
Hi @IsaacEldridge , please have a look at my comments.
With these the doc looks fine to me.
Best,
@PabloCamino

2022-04-22 16:05 UTC, PabloCamino commented on modules/ROOT/pages/manage-proxy.adoc
> +To configure a proxy for the API Manager Agent, add the following properties to the application:
We should add this clarification:
«Mule applications that are managed on API Manager can use a proxy for that communication. This proxy configuration is specific to each Mule application, even if you are using the same for all of them. Also this setting is independent from the application level proxy that application uses to communicate with external endpoints other than API Manager.»
And then the current text.

This is kind of a shortcoming, based on the current documents. The proxy between app <-> API manager needs to be set on each application deployed, there is no global setting. And is not the same as the other application level proxy used between app <-> elsewhere.

2022-04-22 17:15 UTC, PabloCamino approved these changes, later dismissed
Looks great. Hope customers also find it clearer.

2022-04-25 18:03 UTC, rtom-mulesoft submitted a review, later dismissed

2022-04-26 16:25 UTC, bjoson-mulesoft commented on modules/ROOT/pages/manage-proxy.adoc
> +You can configure HTTP and HTTPS proxies for outbound components can communicate with the control plane.
this needs to be updated so that the sentence works -- either "so that outbound components can" or "components to communicate"

2022-04-26 16:25 UTC, bjoson-mulesoft submitted a review, later dismissed

2022-04-26 16:26 UTC, IsaacEldridge commented on modules/ROOT/pages/manage-proxy.adoc
> +You can configure HTTP and HTTPS proxies for outbound components can communicate with the control plane.
```suggestion
You can configure HTTP and HTTPS proxies so that outbound components can communicate with the control plane. 
```

2022-04-26 16:29 UTC, bjoson-mulesoft approved these changes

2022-04-26 16:30 UTC, merged