W-12415285-rtf-authorized-namespaces-openshift-kt
mulesoft/docs-runtime-fabric pull request #940
Opened 2023-01-20 23:12 UTC by kevintroller

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-01-21 00:20 UTC, digvijaysk19 requested changes

2023-01-21 00:20 UTC, digvijaysk19 commented on modules/ROOT/pages/install-openshift.adoc
> +. Apply the following RoleBinding template to name rtf an any additional namespace:
see a couple of typos:
How about this one: 
`Apply the following RoleBinding template to rtf namespace and any additional namespaces:`

2023-01-21 00:20 UTC, digvijaysk19 commented on modules/ROOT/pages/install-openshift.adoc
> +  namespace: <app-namespace-name>
Let's call it `<additional-namespace>`

2023-01-23 16:17 UTC, JennyHajee approved these changes

2023-01-23 17:02 UTC, digvijaysk19 approved these changes
LGTM

2023-01-24 00:11 UTC, merged